/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.pv168.autorental.gui;

import cz.muni.fi.pv168.autorental.backend.*;
import java.awt.Dimension;
import org.apache.commons.dbcp.BasicDataSource;

import javax.swing.*;
import java.math.BigDecimal;
import java.util.List;
import java.util.Locale;
import javax.swing.table.TableColumn;

/**
 *
 * @author strajkaaaa
 */
public class Autorental extends javax.swing.JFrame {

    BasicDataSource basicDataSource = new BasicDataSource();
    
    RentManager rentManager;
    CustomerManager customerManager;
    CarManager carManager;
    
    RentTableModel rentTableModel;
    CustomerTableModel customerTableModel;
    CarTableModel carTableModel;
    
    private AppSwingWorker appSwingWorker;
    private class AppSwingWorker extends SwingWorker<Void, Object> {

	@Override
	protected Void doInBackground() throws Exception {
	    
	    rentManager	    = new RentManagerImpl(basicDataSource);
	    customerManager = new CustomerManagerImpl(basicDataSource);
	    carManager	    = new CarManagerImpl(basicDataSource);
	    
	    rentTableModel     = (RentTableModel) rents_table.getModel();
	    customerTableModel = (CustomerTableModel) customers_table.getModel();
	    carTableModel      = (CarTableModel) cars_table.getModel();
	    
	    for (Rent rent : rentManager.findAllRents()) {
		publish(rent);
	    }
	    for (Customer customer : customerManager.findAllCustomers()) {
		publish(customer);
	    }
	    for (Car car : carManager.findAllCars()) {
		publish(car);
	    }
	    
	    return null;
	}
	
	@Override
	protected void process(List<Object> items) {
	    for (Object obj : items) {
		if (obj instanceof Rent) {
		    rentTableModel.addRent((Rent) obj);
		} else if (obj instanceof Customer) {
		    customerTableModel.addCustomer((Customer) obj);
		} else if (obj instanceof Car) {
		    carTableModel.addCar((Car) obj);
		} else {
		    String msg = "Undefined Object to process";
		    throw new IllegalArgumentException(msg);
		}
	    }
	}
    }

    public Autorental() {
	Locale.setDefault(new Locale("cs"));
	initComponents();
	
	basicDataSource.setUrl("jdbc:derby://localhost:1527/autorental");
	basicDataSource.setUsername("app");
	basicDataSource.setPassword("app");

	appSwingWorker = new AppSwingWorker();
	appSwingWorker.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_rents = new javax.swing.JDialog();
        dialog_rents_idLabel = new javax.swing.JLabel();
        dialog_rents_idInput = new javax.swing.JTextField();
        dialog_rents_customerLabel = new javax.swing.JLabel();
        dialog_rents_customerInput = new javax.swing.JTextField();
        dialog_rents_carLabel = new javax.swing.JLabel();
        dialog_rents_carInput = new javax.swing.JTextField();
        dialog_rents_fromLabel = new javax.swing.JLabel();
        dialog_rents_fromInput = new javax.swing.JTextField();
        dialog_rents_toLabel = new javax.swing.JLabel();
        dialog_rents_toInput = new javax.swing.JTextField();
        dialog_rents_costLabel = new javax.swing.JLabel();
        dialog_rents_costInput = new javax.swing.JTextField();
        dialog_rents_calculate = new javax.swing.JButton();
        dialog_rents_cancel = new javax.swing.JButton();
        dialog_rents_submit = new javax.swing.JButton();
        dialog_customers = new javax.swing.JDialog();
        dialog_customers_idLabel = new javax.swing.JLabel();
        dialog_customers_idInput = new javax.swing.JTextField();
        dialog_customers_firstnameLabel = new javax.swing.JLabel();
        dialog_customers_firstnameInput = new javax.swing.JTextField();
        dialog_customers_lastnameLabel = new javax.swing.JLabel();
        dialog_customers_lastnameInput = new javax.swing.JTextField();
        dialog_customers_birthLabel = new javax.swing.JLabel();
        dialog_customers_birthInput = new javax.swing.JTextField();
        dialog_customers_emailLabel = new javax.swing.JLabel();
        dialog_customers_emailInput = new javax.swing.JTextField();
        dialog_customers_cancel = new javax.swing.JButton();
        dialog_customers_submit = new javax.swing.JButton();
        dialog_cars = new javax.swing.JDialog();
        dialog_cars_idLabel = new javax.swing.JLabel();
        dialog_cars_idInput = new javax.swing.JTextField();
        dialog_cars_modelLabel = new javax.swing.JLabel();
        dialog_cars_modelInput = new javax.swing.JTextField();
        dialog_cars_plateLabel = new javax.swing.JLabel();
        dialog_cars_plateInput = new javax.swing.JTextField();
        dialog_cars_feeLabel = new javax.swing.JLabel();
        dialog_cars_feeInput = new javax.swing.JTextField();
        dialog_cars_submit = new javax.swing.JButton();
        dialog_cars_cancel = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        header_title = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        rents = new javax.swing.JPanel();
        rents_scroll = new javax.swing.JScrollPane();
        rents_table = new javax.swing.JTable();
        rents_add = new javax.swing.JButton();
        rents_update = new javax.swing.JButton();
        rents_delete = new javax.swing.JButton();
        rents_title = new javax.swing.JLabel();
        customers = new javax.swing.JPanel();
        customers_scroll = new javax.swing.JScrollPane();
        customers_table = new javax.swing.JTable();
        customers_add = new javax.swing.JButton();
        customers_update = new javax.swing.JButton();
        customers_delete = new javax.swing.JButton();
        customers_title = new javax.swing.JLabel();
        customers_use = new javax.swing.JButton();
        cars = new javax.swing.JPanel();
        cars_scroll = new javax.swing.JScrollPane();
        cars_table = new javax.swing.JTable();
        cars_add = new javax.swing.JButton();
        cars_update = new javax.swing.JButton();
        cars_delete = new javax.swing.JButton();
        cars_title = new javax.swing.JLabel();
        cars_use = new javax.swing.JButton();

        dialog_rents.setResizable(false);

        dialog_rents_idLabel.setText("ID");

        dialog_rents_idInput.setEnabled(false);
        dialog_rents_idInput.setPreferredSize(new java.awt.Dimension(200, 28));
        dialog_rents_idInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog_rents_idInputActionPerformed(evt);
            }
        });

        dialog_rents_customerLabel.setText("Customer ID");

        dialog_rents_carLabel.setText("Car ID");

        dialog_rents_fromLabel.setText("From");

        dialog_rents_fromInput.setPreferredSize(new java.awt.Dimension(200, 28));

        dialog_rents_toLabel.setText("To");

        dialog_rents_toInput.setPreferredSize(new java.awt.Dimension(200, 28));

        dialog_rents_costLabel.setText("Cost");

        dialog_rents_costInput.setPreferredSize(new java.awt.Dimension(200, 28));

        dialog_rents_calculate.setText("Calculate");
        dialog_rents_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog_rents_calculateActionPerformed(evt);
            }
        });

        dialog_rents_cancel.setText("Cancel");
        dialog_rents_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog_rents_cancelActionPerformed(evt);
            }
        });

        dialog_rents_submit.setText("Submit");
        dialog_rents_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog_rents_submitActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout dialog_rentsLayout = new org.jdesktop.layout.GroupLayout(dialog_rents.getContentPane());
        dialog_rents.getContentPane().setLayout(dialog_rentsLayout);
        dialog_rentsLayout.setHorizontalGroup(
            dialog_rentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dialog_rentsLayout.createSequentialGroup()
                .addContainerGap()
                .add(dialog_rentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, dialog_rentsLayout.createSequentialGroup()
                        .add(dialog_rents_calculate)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 71, Short.MAX_VALUE)
                        .add(dialog_rents_cancel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(dialog_rents_submit))
                    .add(dialog_rentsLayout.createSequentialGroup()
                        .add(dialog_rentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, dialog_rents_costLabel)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, dialog_rents_toLabel)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, dialog_rents_fromLabel)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, dialog_rents_carLabel)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, dialog_rents_customerLabel)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, dialog_rents_idLabel))
                        .add(12, 12, 12)
                        .add(dialog_rentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(dialog_rents_fromInput, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(dialog_rents_costInput, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(dialog_rents_idInput, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(dialog_rents_toInput, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(dialog_rents_customerInput)
                            .add(dialog_rents_carInput))))
                .addContainerGap())
        );
        dialog_rentsLayout.setVerticalGroup(
            dialog_rentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dialog_rentsLayout.createSequentialGroup()
                .addContainerGap()
                .add(dialog_rentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dialog_rents_idInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(dialog_rents_idLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialog_rentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dialog_rents_customerLabel)
                    .add(dialog_rents_customerInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialog_rentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dialog_rents_carLabel)
                    .add(dialog_rents_carInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialog_rentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dialog_rents_fromInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(dialog_rents_fromLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialog_rentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dialog_rents_toInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(dialog_rents_toLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialog_rentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dialog_rents_costInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(dialog_rents_costLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialog_rentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dialog_rents_submit)
                    .add(dialog_rents_cancel)
                    .add(dialog_rents_calculate))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialog_customers.setResizable(false);

        dialog_customers_idLabel.setText("ID");

        dialog_customers_idInput.setEnabled(false);
        dialog_customers_idInput.setPreferredSize(new java.awt.Dimension(200, 28));
        dialog_customers_idInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog_customers_idInputActionPerformed(evt);
            }
        });

        dialog_customers_firstnameLabel.setText("Firstname");

        dialog_customers_firstnameInput.setPreferredSize(new java.awt.Dimension(200, 28));
        dialog_customers_firstnameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog_customers_firstnameInputActionPerformed(evt);
            }
        });

        dialog_customers_lastnameLabel.setText("Lastname");

        dialog_customers_lastnameInput.setPreferredSize(new java.awt.Dimension(200, 28));

        dialog_customers_birthLabel.setText("Birth");

        dialog_customers_birthInput.setPreferredSize(new java.awt.Dimension(200, 28));

        dialog_customers_emailLabel.setText("E-mail");

        dialog_customers_emailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog_customers_emailInputActionPerformed(evt);
            }
        });

        dialog_customers_cancel.setText("Cancel");
        dialog_customers_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog_customers_cancelActionPerformed(evt);
            }
        });

        dialog_customers_submit.setText("Submit");
        dialog_customers_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog_customers_submitActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout dialog_customersLayout = new org.jdesktop.layout.GroupLayout(dialog_customers.getContentPane());
        dialog_customers.getContentPane().setLayout(dialog_customersLayout);
        dialog_customersLayout.setHorizontalGroup(
            dialog_customersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dialog_customersLayout.createSequentialGroup()
                .addContainerGap()
                .add(dialog_customersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(dialog_customersLayout.createSequentialGroup()
                        .add(dialog_customersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, dialog_customers_emailLabel)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, dialog_customers_birthLabel)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, dialog_customers_lastnameLabel)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, dialog_customers_firstnameLabel)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, dialog_customers_idLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(dialog_customersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(dialog_customers_lastnameInput, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                            .add(dialog_customers_birthInput, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(dialog_customers_firstnameInput, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(dialog_customers_idInput, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(dialog_customers_emailInput)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, dialog_customersLayout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(dialog_customers_cancel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(dialog_customers_submit)))
                .addContainerGap())
        );
        dialog_customersLayout.setVerticalGroup(
            dialog_customersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dialog_customersLayout.createSequentialGroup()
                .addContainerGap()
                .add(dialog_customersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dialog_customers_idLabel)
                    .add(dialog_customers_idInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialog_customersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dialog_customers_firstnameLabel)
                    .add(dialog_customers_firstnameInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialog_customersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dialog_customers_lastnameLabel)
                    .add(dialog_customers_lastnameInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialog_customersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dialog_customers_birthLabel)
                    .add(dialog_customers_birthInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialog_customersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dialog_customers_emailInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(dialog_customers_emailLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialog_customersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dialog_customers_submit)
                    .add(dialog_customers_cancel))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialog_cars.setResizable(false);

        dialog_cars_idLabel.setText("ID");

        dialog_cars_idInput.setEnabled(false);
        dialog_cars_idInput.setPreferredSize(new java.awt.Dimension(200, 28));
        dialog_cars_idInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog_cars_idInputActionPerformed(evt);
            }
        });

        dialog_cars_modelLabel.setText("Model");

        dialog_cars_modelInput.setPreferredSize(new java.awt.Dimension(200, 28));
        dialog_cars_modelInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog_cars_modelInputActionPerformed(evt);
            }
        });

        dialog_cars_plateLabel.setText("Plate");

        dialog_cars_plateInput.setPreferredSize(new java.awt.Dimension(200, 28));

        dialog_cars_feeLabel.setText("Fee");

        dialog_cars_feeInput.setPreferredSize(new java.awt.Dimension(200, 28));

        dialog_cars_submit.setText("Submit");
        dialog_cars_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog_cars_submitActionPerformed(evt);
            }
        });

        dialog_cars_cancel.setText("Cancel");
        dialog_cars_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog_cars_cancelActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout dialog_carsLayout = new org.jdesktop.layout.GroupLayout(dialog_cars.getContentPane());
        dialog_cars.getContentPane().setLayout(dialog_carsLayout);
        dialog_carsLayout.setHorizontalGroup(
            dialog_carsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dialog_carsLayout.createSequentialGroup()
                .addContainerGap()
                .add(dialog_carsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, dialog_carsLayout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(dialog_cars_cancel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(dialog_cars_submit))
                    .add(dialog_carsLayout.createSequentialGroup()
                        .add(dialog_carsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, dialog_cars_modelLabel)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, dialog_cars_idLabel)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, dialog_cars_plateLabel)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, dialog_cars_feeLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(dialog_carsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(dialog_cars_idInput, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                            .add(dialog_cars_modelInput, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(dialog_cars_plateInput, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(dialog_cars_feeInput, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        dialog_carsLayout.setVerticalGroup(
            dialog_carsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dialog_carsLayout.createSequentialGroup()
                .addContainerGap()
                .add(dialog_carsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dialog_cars_idLabel)
                    .add(dialog_cars_idInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialog_carsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dialog_cars_modelLabel)
                    .add(dialog_cars_modelInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialog_carsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dialog_cars_plateLabel)
                    .add(dialog_cars_plateInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialog_carsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dialog_cars_feeLabel)
                    .add(dialog_cars_feeInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dialog_carsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dialog_cars_submit)
                    .add(dialog_cars_cancel))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 829));

        header.setPreferredSize(new java.awt.Dimension(1085, 40));

        header_title.setFont(header_title.getFont().deriveFont(header_title.getFont().getStyle() | java.awt.Font.BOLD, header_title.getFont().getSize()+12));
        header_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header_title.setText("jAutorentalApp");

        org.jdesktop.layout.GroupLayout headerLayout = new org.jdesktop.layout.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap()
                .add(header_title, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1119, Short.MAX_VALUE)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(header_title, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26))
        );

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        rents_table.setModel(new RentTableModel());
        rents_table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TableColumn rents_col_id = rents_table.getColumnModel().getColumn(0);
        rents_col_id.setMaxWidth(40);
        TableColumn rents_col_customer = rents_table.getColumnModel().getColumn(1);
        TableColumn rents_col_car = rents_table.getColumnModel().getColumn(2);
        TableColumn rents_col_from = rents_table.getColumnModel().getColumn(3);
        rents_col_from.setMaxWidth(100);
        TableColumn rents_col_to = rents_table.getColumnModel().getColumn(4);
        rents_col_to.setMaxWidth(100);
        TableColumn rents_col_cost = rents_table.getColumnModel().getColumn(5);
        rents_col_cost.setMaxWidth(100);
        rents_scroll.setViewportView(rents_table);

        rents_add.setText("Add");
        rents_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rents_addActionPerformed(evt);
            }
        });

        rents_update.setText("Update");
        rents_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rents_updateActionPerformed(evt);
            }
        });

        rents_delete.setText("Delete");

        rents_title.setFont(rents_title.getFont().deriveFont(rents_title.getFont().getStyle() | java.awt.Font.BOLD, rents_title.getFont().getSize()+6));
        rents_title.setText("Rents");

        org.jdesktop.layout.GroupLayout rentsLayout = new org.jdesktop.layout.GroupLayout(rents);
        rents.setLayout(rentsLayout);
        rentsLayout.setHorizontalGroup(
            rentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, rentsLayout.createSequentialGroup()
                .addContainerGap()
                .add(rents_scroll)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(rents_title, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(rents_update, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(rents_delete, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(rents_add, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        rentsLayout.setVerticalGroup(
            rentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(rentsLayout.createSequentialGroup()
                .addContainerGap()
                .add(rentsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(rentsLayout.createSequentialGroup()
                        .add(rents_title)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(rents_add)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(rents_update)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(rents_delete)
                        .add(0, 108, Short.MAX_VALUE))
                    .add(rents_scroll, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        customers_table.setModel(new CustomerTableModel());
        customers_table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TableColumn customers_col_id = customers_table.getColumnModel().getColumn(0);
        customers_col_id.setMaxWidth(40);
        TableColumn customers_col_firstname = customers_table.getColumnModel().getColumn(1);
        TableColumn customers_col_lastname = customers_table.getColumnModel().getColumn(2);
        TableColumn customers_col_birth = customers_table.getColumnModel().getColumn(3);
        customers_col_birth.setMaxWidth(100);
        TableColumn customers_col_email = customers_table.getColumnModel().getColumn(4);
        customers_scroll.setViewportView(customers_table);

        customers_add.setText("Add");
        customers_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customers_addActionPerformed(evt);
            }
        });

        customers_update.setText("Update");

        customers_delete.setText("Delete");

        customers_title.setFont(customers_title.getFont().deriveFont(customers_title.getFont().getStyle() | java.awt.Font.BOLD, customers_title.getFont().getSize()+6));
        customers_title.setText("Customers");

        customers_use.setText("Use");
        customers_use.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customers_useActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout customersLayout = new org.jdesktop.layout.GroupLayout(customers);
        customers.setLayout(customersLayout);
        customersLayout.setHorizontalGroup(
            customersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, customersLayout.createSequentialGroup()
                .addContainerGap()
                .add(customers_scroll, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(customersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(customers_title, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(customers_update, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(customers_delete, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(customers_add, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(customers_use, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        customersLayout.setVerticalGroup(
            customersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(customersLayout.createSequentialGroup()
                .addContainerGap()
                .add(customersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(customersLayout.createSequentialGroup()
                        .add(customers_title)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(customers_add)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(customers_update)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(customers_delete)
                        .add(18, 18, 18)
                        .add(customers_use)
                        .add(0, 61, Short.MAX_VALUE))
                    .add(customers_scroll, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        cars_table.setModel(new CarTableModel());
        cars_table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TableColumn cars_col_id = cars_table.getColumnModel().getColumn(0);
        cars_col_id.setMaxWidth(40);
        TableColumn cars_col_model = cars_table.getColumnModel().getColumn(1);
        TableColumn cars_col_plate = cars_table.getColumnModel().getColumn(2);
        cars_col_plate.setMaxWidth(120);
        TableColumn cars_col_fee = cars_table.getColumnModel().getColumn(3);
        cars_col_fee.setMaxWidth(100);
        cars_scroll.setViewportView(cars_table);

        cars_add.setText("Add");
        cars_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cars_addActionPerformed(evt);
            }
        });

        cars_update.setText("Update");
        cars_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cars_updateActionPerformed(evt);
            }
        });

        cars_delete.setText("Delete");

        cars_title.setFont(cars_title.getFont().deriveFont(cars_title.getFont().getStyle() | java.awt.Font.BOLD, cars_title.getFont().getSize()+6));
        cars_title.setText("Cars");

        cars_use.setText("Use");

        org.jdesktop.layout.GroupLayout carsLayout = new org.jdesktop.layout.GroupLayout(cars);
        cars.setLayout(carsLayout);
        carsLayout.setHorizontalGroup(
            carsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, carsLayout.createSequentialGroup()
                .addContainerGap()
                .add(cars_scroll, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(carsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(cars_title, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cars_update, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cars_delete, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cars_add, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, cars_use, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        carsLayout.setVerticalGroup(
            carsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(carsLayout.createSequentialGroup()
                .addContainerGap()
                .add(carsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(carsLayout.createSequentialGroup()
                        .add(cars_title)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cars_add)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cars_update)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cars_delete)
                        .add(18, 18, 18)
                        .add(cars_use)
                        .add(0, 82, Short.MAX_VALUE))
                    .add(cars_scroll, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout contentLayout = new org.jdesktop.layout.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(contentLayout.createSequentialGroup()
                .addContainerGap()
                .add(contentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(cars, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(customers, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(rents, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(contentLayout.createSequentialGroup()
                .addContainerGap()
                .add(rents, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(customers, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cars, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(content, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dialog_cars_modelInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialog_cars_modelInputActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_dialog_cars_modelInputActionPerformed

    private void dialog_cars_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialog_cars_cancelActionPerformed
	dialog_cars.setVisible(false);
    }//GEN-LAST:event_dialog_cars_cancelActionPerformed

    private void dialog_cars_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialog_cars_submitActionPerformed
	Car car = new Car();
	car.setModel(dialog_cars_modelInput.getText());
	car.setPlate(dialog_cars_plateInput.getText());
	car.setFee(BigDecimal.valueOf(Double.parseDouble(dialog_cars_feeInput.getText())).setScale(2));
	carManager.addCar(car);
	carTableModel.addCar(car);
	dialog_cars_modelInput.setText("");
	dialog_cars_plateInput.setText("");
	dialog_cars_feeInput.setText("");
    }//GEN-LAST:event_dialog_cars_submitActionPerformed

    private void rents_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rents_addActionPerformed
	dialog_rents.setVisible(true);
        dialog_rents.setSize(new Dimension(400, 300)); // TODO better
    }//GEN-LAST:event_rents_addActionPerformed

    private void customers_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customers_addActionPerformed
        dialog_customers.setVisible(true);
        dialog_customers.setSize(new Dimension(400, 300)); // TODO better
    }//GEN-LAST:event_customers_addActionPerformed

    private void cars_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cars_addActionPerformed
        dialog_cars.setVisible(true);
        dialog_cars.setSize(new Dimension(400, 300)); // TODO better
    }//GEN-LAST:event_cars_addActionPerformed

    private void cars_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cars_updateActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_cars_updateActionPerformed

    private void dialog_cars_idInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialog_cars_idInputActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_dialog_cars_idInputActionPerformed

    private void dialog_customers_idInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialog_customers_idInputActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_dialog_customers_idInputActionPerformed

    private void dialog_customers_firstnameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialog_customers_firstnameInputActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_dialog_customers_firstnameInputActionPerformed

    private void dialog_customers_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialog_customers_submitActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_dialog_customers_submitActionPerformed

    private void dialog_customers_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialog_customers_cancelActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_dialog_customers_cancelActionPerformed

    private void dialog_rents_idInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialog_rents_idInputActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_dialog_rents_idInputActionPerformed

    private void dialog_rents_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialog_rents_submitActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_dialog_rents_submitActionPerformed

    private void dialog_rents_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialog_rents_cancelActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_dialog_rents_cancelActionPerformed

    private void dialog_rents_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialog_rents_calculateActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_dialog_rents_calculateActionPerformed

    private void dialog_customers_emailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialog_customers_emailInputActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_dialog_customers_emailInputActionPerformed

    private void rents_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rents_updateActionPerformed
        dialog_rents.setVisible(true);
        dialog_rents.setSize(new Dimension(400, 300)); // TODO better
        dialog_rents_idInput.setText(String.valueOf(rentTableModel.getValueAt(rents_table.getSelectedRow(), 0)));
        dialog_rents_customerInput.setText(String.valueOf(rentTableModel.getValueAt(rents_table.getSelectedRow(), 1)));
        dialog_rents_carInput.setText(String.valueOf(rentTableModel.getValueAt(rents_table.getSelectedRow(), 2)));
        dialog_rents_fromInput.setText(String.valueOf(rentTableModel.getValueAt(rents_table.getSelectedRow(), 3)));
        dialog_rents_toInput.setText(String.valueOf(rentTableModel.getValueAt(rents_table.getSelectedRow(), 4)));
        dialog_rents_costInput.setText(String.valueOf(rentTableModel.getValueAt(rents_table.getSelectedRow(), 5)));
    }//GEN-LAST:event_rents_updateActionPerformed

    private void customers_useActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customers_useActionPerformed
        dialog_rents_customerInput.setText(String.valueOf(customerTableModel.getValueAt(customers_table.getSelectedRow(), 0)));
    }//GEN-LAST:event_customers_useActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/*
	 * Set the Nimbus look and feel
	 */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
	 * If Nimbus (introduced in Java SE 6) is not available, stay with the
	 * default look and feel. For details see
	 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(Autorental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(Autorental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(Autorental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(Autorental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/*
	 * Create and display the form
	 */
	java.awt.EventQueue.invokeLater(new Runnable() {

	    public void run() {
		new Autorental().setVisible(true);
	    }
	});
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cars;
    private javax.swing.JButton cars_add;
    private javax.swing.JButton cars_delete;
    private javax.swing.JScrollPane cars_scroll;
    private javax.swing.JTable cars_table;
    private javax.swing.JLabel cars_title;
    private javax.swing.JButton cars_update;
    private javax.swing.JButton cars_use;
    private javax.swing.JPanel content;
    private javax.swing.JPanel customers;
    private javax.swing.JButton customers_add;
    private javax.swing.JButton customers_delete;
    private javax.swing.JScrollPane customers_scroll;
    private javax.swing.JTable customers_table;
    private javax.swing.JLabel customers_title;
    private javax.swing.JButton customers_update;
    private javax.swing.JButton customers_use;
    private javax.swing.JDialog dialog_cars;
    private javax.swing.JButton dialog_cars_cancel;
    private javax.swing.JTextField dialog_cars_feeInput;
    private javax.swing.JLabel dialog_cars_feeLabel;
    private javax.swing.JTextField dialog_cars_idInput;
    private javax.swing.JLabel dialog_cars_idLabel;
    private javax.swing.JTextField dialog_cars_modelInput;
    private javax.swing.JLabel dialog_cars_modelLabel;
    private javax.swing.JTextField dialog_cars_plateInput;
    private javax.swing.JLabel dialog_cars_plateLabel;
    private javax.swing.JButton dialog_cars_submit;
    private javax.swing.JDialog dialog_customers;
    private javax.swing.JTextField dialog_customers_birthInput;
    private javax.swing.JLabel dialog_customers_birthLabel;
    private javax.swing.JButton dialog_customers_cancel;
    private javax.swing.JTextField dialog_customers_emailInput;
    private javax.swing.JLabel dialog_customers_emailLabel;
    private javax.swing.JTextField dialog_customers_firstnameInput;
    private javax.swing.JLabel dialog_customers_firstnameLabel;
    private javax.swing.JTextField dialog_customers_idInput;
    private javax.swing.JLabel dialog_customers_idLabel;
    private javax.swing.JTextField dialog_customers_lastnameInput;
    private javax.swing.JLabel dialog_customers_lastnameLabel;
    private javax.swing.JButton dialog_customers_submit;
    private javax.swing.JDialog dialog_rents;
    private javax.swing.JButton dialog_rents_calculate;
    private javax.swing.JButton dialog_rents_cancel;
    private javax.swing.JTextField dialog_rents_carInput;
    private javax.swing.JLabel dialog_rents_carLabel;
    private javax.swing.JTextField dialog_rents_costInput;
    private javax.swing.JLabel dialog_rents_costLabel;
    private javax.swing.JTextField dialog_rents_customerInput;
    private javax.swing.JLabel dialog_rents_customerLabel;
    private javax.swing.JTextField dialog_rents_fromInput;
    private javax.swing.JLabel dialog_rents_fromLabel;
    private javax.swing.JTextField dialog_rents_idInput;
    private javax.swing.JLabel dialog_rents_idLabel;
    private javax.swing.JButton dialog_rents_submit;
    private javax.swing.JTextField dialog_rents_toInput;
    private javax.swing.JLabel dialog_rents_toLabel;
    private javax.swing.JPanel header;
    private javax.swing.JLabel header_title;
    private javax.swing.JPanel rents;
    private javax.swing.JButton rents_add;
    private javax.swing.JButton rents_delete;
    private javax.swing.JScrollPane rents_scroll;
    private javax.swing.JTable rents_table;
    private javax.swing.JLabel rents_title;
    private javax.swing.JButton rents_update;
    // End of variables declaration//GEN-END:variables
}
