/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.pv168.autorental.gui;

/**
 *
 * @author strajk
 */
public class GUI_backup extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI_backup() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNorth = new javax.swing.JPanel();
        jLabelAppTitle = new javax.swing.JLabel();
        jPanelSouth = new javax.swing.JPanel();
        jPanelWest = new javax.swing.JPanel();
        jLabelRentsTitle = new javax.swing.JLabel();
        jPanelRentsStats = new javax.swing.JPanel();
        jPanelEast = new javax.swing.JPanel();
        jButtonActionAdd = new javax.swing.JButton();
        jButtonActionUpdate = new javax.swing.JButton();
        jButtonActionDelete = new javax.swing.JButton();
        jPanelCenter = new javax.swing.JPanel();
        jScrollPaneRentsScroll = new javax.swing.JScrollPane();
        jTableRentsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelNorth.setPreferredSize(new java.awt.Dimension(1085, 50));

        jLabelAppTitle.setFont(jLabelAppTitle.getFont().deriveFont(jLabelAppTitle.getFont().getStyle() | java.awt.Font.BOLD, jLabelAppTitle.getFont().getSize()+12));
        jLabelAppTitle.setText("jAutorentalApp");

        org.jdesktop.layout.GroupLayout jPanelNorthLayout = new org.jdesktop.layout.GroupLayout(jPanelNorth);
        jPanelNorth.setLayout(jPanelNorthLayout);
        jPanelNorthLayout.setHorizontalGroup(
            jPanelNorthLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelNorthLayout.createSequentialGroup()
                .add(473, 473, 473)
                .add(jLabelAppTitle)
                .addContainerGap(417, Short.MAX_VALUE))
        );
        jPanelNorthLayout.setVerticalGroup(
            jPanelNorthLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelNorthLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabelAppTitle)
                .add(39, 39, 39))
        );

        getContentPane().add(jPanelNorth, java.awt.BorderLayout.PAGE_START);

        jPanelSouth.setPreferredSize(new java.awt.Dimension(1085, 50));

        org.jdesktop.layout.GroupLayout jPanelSouthLayout = new org.jdesktop.layout.GroupLayout(jPanelSouth);
        jPanelSouth.setLayout(jPanelSouthLayout);
        jPanelSouthLayout.setHorizontalGroup(
            jPanelSouthLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1085, Short.MAX_VALUE)
        );
        jPanelSouthLayout.setVerticalGroup(
            jPanelSouthLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelSouth, java.awt.BorderLayout.PAGE_END);

        jPanelWest.setPreferredSize(new java.awt.Dimension(220, 576));

        jLabelRentsTitle.setFont(jLabelRentsTitle.getFont().deriveFont(jLabelRentsTitle.getFont().getStyle() | java.awt.Font.BOLD, jLabelRentsTitle.getFont().getSize()+4));
        jLabelRentsTitle.setText("Rents");

        jPanelRentsStats.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelRentsStats.setPreferredSize(new java.awt.Dimension(0, 150));

        org.jdesktop.layout.GroupLayout jPanelRentsStatsLayout = new org.jdesktop.layout.GroupLayout(jPanelRentsStats);
        jPanelRentsStats.setLayout(jPanelRentsStatsLayout);
        jPanelRentsStatsLayout.setHorizontalGroup(
            jPanelRentsStatsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );
        jPanelRentsStatsLayout.setVerticalGroup(
            jPanelRentsStatsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 146, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout jPanelWestLayout = new org.jdesktop.layout.GroupLayout(jPanelWest);
        jPanelWest.setLayout(jPanelWestLayout);
        jPanelWestLayout.setHorizontalGroup(
            jPanelWestLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelWestLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelWestLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanelRentsStats, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .add(jLabelRentsTitle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelWestLayout.setVerticalGroup(
            jPanelWestLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelWestLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelRentsTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelRentsStats, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(548, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelWest, java.awt.BorderLayout.LINE_START);

        jButtonActionAdd.setText("Add");
        jButtonActionAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionAddActionPerformed(evt);
            }
        });

        jButtonActionUpdate.setText("Update");

        jButtonActionDelete.setText("Delete");

        org.jdesktop.layout.GroupLayout jPanelEastLayout = new org.jdesktop.layout.GroupLayout(jPanelEast);
        jPanelEast.setLayout(jPanelEastLayout);
        jPanelEastLayout.setHorizontalGroup(
            jPanelEastLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEastLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelEastLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButtonActionAdd, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jButtonActionUpdate, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .add(jButtonActionDelete, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelEastLayout.setVerticalGroup(
            jPanelEastLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEastLayout.createSequentialGroup()
                .addContainerGap()
                .add(jButtonActionAdd)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonActionUpdate)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonActionDelete)
                .addContainerGap(645, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelEast, java.awt.BorderLayout.LINE_END);

        jTableRentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneRentsScroll.setViewportView(jTableRentsTable);

        org.jdesktop.layout.GroupLayout jPanelCenterLayout = new org.jdesktop.layout.GroupLayout(jPanelCenter);
        jPanelCenter.setLayout(jPanelCenterLayout);
        jPanelCenterLayout.setHorizontalGroup(
            jPanelCenterLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPaneRentsScroll, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCenterLayout.setVerticalGroup(
            jPanelCenterLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPaneRentsScroll, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(544, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActionAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionAddActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_jButtonActionAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/*
	 * Set the Nimbus look and feel
	 */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
	 * If Nimbus (introduced in Java SE 6) is not available, stay with the
	 * default look and feel. For details see
	 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(GUI_backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(GUI_backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(GUI_backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(GUI_backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/*
	 * Create and display the form
	 */
	java.awt.EventQueue.invokeLater(new Runnable() {

	    public void run() {
		new GUI_backup().setVisible(true);
	    }
	});
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActionAdd;
    private javax.swing.JButton jButtonActionDelete;
    private javax.swing.JButton jButtonActionUpdate;
    private javax.swing.JLabel jLabelAppTitle;
    private javax.swing.JLabel jLabelRentsTitle;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelEast;
    private javax.swing.JPanel jPanelNorth;
    private javax.swing.JPanel jPanelRentsStats;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JPanel jPanelWest;
    private javax.swing.JScrollPane jScrollPaneRentsScroll;
    private javax.swing.JTable jTableRentsTable;
    // End of variables declaration//GEN-END:variables
}
