/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.pv168.autorental.gui;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.List;
import javax.swing.SwingWorker;

/**
 *
 * @author strajk
 */
public class SwingWorkerExample extends javax.swing.JFrame {

    private MySwingWorker worker;

    private class MySwingWorker extends SwingWorker<Integer, Integer> {

	@Override
	protected Integer doInBackground() throws Exception {
	    int result = 0;
	    for (int i = 0; i <= 100; i++) {
		if (isCancelled()) {
		    break;
		}
		Thread.sleep(10); // Simulate
		result += i;
		publish(i);
		setProgress(i);
	    }
	    return result;
	}

	@Override
	protected void done() {
	    jButtonStart.setEnabled(true);
	    if (!isCancelled()) {
		try {
		    jTextArea1.append("Result is: " + get());
		} catch (Exception ex) {
		    jTextArea1.append("Error: " + ex);
		}
	    }
	}

	@Override
	protected void process(List<Integer> chunks) {
	    jTextArea1.append(chunks.toString() + "\n");
	}
    }
    private PropertyChangeListener progressListener = new PropertyChangeListener() {

	@Override
	public void propertyChange(PropertyChangeEvent evt) {
	    if (evt.getPropertyName().equals("progress")) {
		jProgressBar1.setValue((Integer) evt.getNewValue());
	    }
	}
    };

    public SwingWorkerExample() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">                          
    private void initComponents() {
	jButtonStart = new javax.swing.JButton();
	jButtonCancel = new javax.swing.JButton();
	jProgressBar1 = new javax.swing.JProgressBar();
	jScrollPane1 = new javax.swing.JScrollPane();
	jTextArea1 = new javax.swing.JTextArea();

	setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	jButtonStart.setText("Start");
	jButtonStart.addActionListener(new java.awt.event.ActionListener() {

	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		jButtonStartActionPerformed(evt);
	    }
	});

	jButtonCancel.setText("Cancel");
	jButtonCancel.addActionListener(new java.awt.event.ActionListener() {

	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		jButtonCancelActionPerformed(evt);
	    }
	});

	jTextArea1.setColumns(20);
	jTextArea1.setRows(5);
	jScrollPane1.setViewportView(jTextArea1);

	javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	getContentPane().setLayout(layout);
	layout.setHorizontalGroup(
		layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE).addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE).addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup().addComponent(jButtonStart).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jButtonCancel))).addContainerGap()));
	layout.setVerticalGroup(
		layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap().addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jButtonStart).addComponent(jButtonCancel)).addContainerGap()));
	pack();
    }// </editor-fold>                        

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {
	worker.cancel(false);
    }

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {
	jButtonStart.setEnabled(false);
	worker = new MySwingWorker();
	worker.addPropertyChangeListener(progressListener);
	worker.execute();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	java.awt.EventQueue.invokeLater(new Runnable() {

	    @Override
	    public void run() {
		new SwingWorkerExample().setVisible(true);
	    }
	});
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration                   
}
